services:
  fastapi:
    build: ./app  # Path to your FastAPI app
    container_name: fastapi-server
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    depends_on:
      - db  # Ensure DB starts before FastAPI
    environment:
      DATABASE_URL: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB"  # PostgreSQL connection string
    volumes:
      - ./app:/app  # Mount the FastAPI app directory into the container

  db:
    image: postgis/postgis:15-3.3  # Use PostGIS image
    container_name: postgres-container
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize DB with the init.sql script
    ports:
      - "5999:5999"  # Expose PostgreSQL on port 5432
