version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container_test
    environment:
      POSTGRES_USER: admin               # Database username
      POSTGRES_PASSWORD: password        # Database password
      POSTGRES_DB: myappdb               # Database name
    ports:
      - "5432:5432"                      # Map port 5432 to host
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
