services:
  fastapi:
    build: ./app/backend
    container_name: Server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB"
    volumes:
      - ./app/backend:/app

  db:
    image: postgis/postgis:15-3.3
    container_name: MLM_Database
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: Adminer
    ports:
      - "8081:8080"

  nginx:
    image: nginx:latest
    container_name: Webserver
    ports:
      - "8082:80"
    volumes:
    - ./app/frontend:/usr/share/nginx/html:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro